project:
  type: website

website:
  google-analytics: "G-SGM5SNE7BQ"
  title: "Geospatial Analytics"
  navbar:
    left: 
      - text: Hands-On
        menu:
          - text: Data Wrangling Technique
            href: ho/ho1_1.qmd
          - text: Choropleth Mapping
            href: ho/ho1_2.qmd 
            
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

